# docker-compose.yml
version: '3'
services:
  pyspark:
    build: .
    ports:
      - 8888:8888
    volumes:
      - .:/app
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''"]
    # command: ["bash", "-c", "spark-submit --master local[*] /app/test.py"]